- zapomniałem przegenerować (w)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2229,7 +2229,7 @@ distclean_ekg=""
 
 uninstall_ekg=""
 
-ekgwap=""
+make_ekgwap=""
 
 install_ekgwap=""
 
@@ -3335,8 +3335,12 @@ if test "${enable_wap+set}" = set; then
 fi;
 
   if test "x$enable_wap" = "xyes"; then
-    ekgwap="ekgwap"
+    make_ekgwap="make-ekgwap"
     install_ekgwap="install-ekgwap"
+    cat >>confdefs.h <<\EOF
+#define WITH_WAP 1
+EOF
+
   fi
 
   # Check whether --enable-ioctld or --disable-ioctld was given.
@@ -3450,7 +3454,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3453: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3457: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3623,7 +3627,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3626: error: ambiguous option: $1
+    { { echo "$as_me:3630: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3642,7 +3646,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3645: error: unrecognized option: $1
+  -*) { { echo "$as_me:3649: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3682,7 +3686,7 @@ do
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:3685: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3689: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3798,7 +3802,7 @@ s,@install_ekg@,$install_ekg,;t t
 s,@clean_ekg@,$clean_ekg,;t t
 s,@distclean_ekg@,$distclean_ekg,;t t
 s,@uninstall_ekg@,$uninstall_ekg,;t t
-s,@ekgwap@,$ekgwap,;t t
+s,@make_ekgwap@,$make_ekgwap,;t t
 s,@install_ekgwap@,$install_ekgwap,;t t
 s,@ui_readline_o@,$ui_readline_o,;t t
 s,@ui_ncurses_o@,$ui_ncurses_o,;t t
@@ -3921,7 +3925,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3924: creating $ac_file" >&5
+    { echo "$as_me:3928: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3939,7 +3943,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3942: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3946: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3952,7 +3956,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3955: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3959: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4013,7 +4017,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4016: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4020: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4024,7 +4028,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4027: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4031: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4037,7 +4041,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4040: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4044: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4154,7 +4158,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4157: $ac_file is unchanged" >&5
+      { echo "$as_me:4161: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
