- poprawka błędnych statusów (wielu/w) - porządki w Makefile'ach i configure.in (w)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4621,10 +4621,12 @@ if test "x$with_ioctl" = "xyes"; then
   do_ioctl="ioctl_daemon"
   dioctl=" -DIOCTL "
   install_ioctl="install_ioctl"
+  ioctl_cflags="-DIOCTL_DAEMON_PATH=\\\"\$(prefix)/bin/ioctl_daemon\\\""
 else
   do_ioctl=""
   dioctl=""
   install_ioctl=""
+  ioctl_cflags=""
 fi
 
 # Check whether --with-shared or --without-shared was given.
@@ -4733,7 +4735,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4736: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4738: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4906,7 +4908,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4909: error: ambiguous option: $1
+    { { echo "$as_me:4911: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4925,7 +4927,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4928: error: unrecognized option: $1
+  -*) { { echo "$as_me:4930: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4965,7 +4967,7 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4968: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4970: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5074,6 +5076,7 @@ s,@dioctl@,$dioctl,;t t
 s,@shared@,$shared,;t t
 s,@install_ioctl@,$install_ioctl,;t t
 s,@install_shared@,$install_shared,;t t
+s,@ioctl_cflags@,$ioctl_cflags,;t t
 CEOF
 
 EOF
@@ -5188,7 +5191,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5191: creating $ac_file" >&5
+    { echo "$as_me:5194: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5206,7 +5209,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5209: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5212: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5219,7 +5222,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5222: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5225: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5280,7 +5283,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5283: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5286: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5291,7 +5294,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5294: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5297: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5304,7 +5307,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5307: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5310: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5421,7 +5424,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5424: $ac_file is unchanged" >&5
+      { echo "$as_me:5427: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
